version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: job-service
      POSTGRES_PASSWORD: example
      POSTGRES_DB: jobs
    volumes:
      - ./db/src/main/resources/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  storage:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: job-service
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
  queue:
    image: apache/activemq-artemis
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
  api:
    build:
      context: api
      dockerfile: Dockerfile
    image: api:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - queue
      - storage
    environment:
      DB_HOST: db
      MQ_HOST: queue
      S3_HOST: storage
  scanner:
    build:
      context: scanner
      dockerfile: Dockerfile
    image: scanner:latest
    depends_on:
      - db
      - queue
      - storage
    environment:
      DB_HOST: db
      MQ_HOST: queue
      S3_HOST: storage
  create-buckets:
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set storage http://storage:9000 job-service password;
      /usr/bin/mc mb storage/documents;
      /usr/bin/mc policy set public storage/documents;
      exit 0;
      "
